version: "3.9"

services:
  db:
    image: mysql:8
    container_name: taskflow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: jobportaldb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend/taskflow/taskflow
    container_name: taskflow-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/jobportaldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123

  frontend:
    build: ./frontend
    container_name: taskflow-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  db_data:
